before_install:
 - chmod +x gradlew
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|^(LICENSE)'
   then
     echo "Not running CI since only docs were changed."
     exit
   fi

install: ./gradlew assemble

script: ./gradlew clean build --info

language: java

jdk:
  - oraclejdk11